set(PNG_FOUND ON CACHE BOOL "" FORCE)
set(PNG_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/third_party/libpng CACHE STRING "" FORCE)
set(PNG_LIBRARIES png_static CACHE STRING "" FORCE)
set(PNG_LIBRARY png_static CACHE STRING "" FORCE)
